# Generated by Django 6.0.7 on 2026-07-22 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=36, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_body', models.JSONField(blank=True, help_text='Sensitive fields redacted before storage.', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Only populated when status_code >= 500.', null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_request_user_id_6fe1fb_idx'), models.Index(fields=['status_code', 'created_at'], name='api_request_status__28e84a_idx'), models.Index(fields=['created_at'], name='api_request_created_2205b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=60)),
                ('request_id', models.CharField(blank=True, help_text='Ties this event to the HTTP request that caused it (core.middleware assigns one UUID per request).', max_length=36, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null when the event has no authenticated actor yet (e.g. a failed login attempt against an unknown email).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['event', 'created_at'], name='audit_log_event_60c9cc_idx'), models.Index(fields=['ip_address', 'created_at'], name='audit_log_ip_addr_f5a3a9_idx'), models.Index(fields=['request_id'], name='audit_log_request_a46c86_idx')],
            },
        ),
    ]
