# Generated by Django 5.2.16 on 2026-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationread',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
