# Generated by Django 5.2.16 on 2026-07-31 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificationread_dismissed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Only set when someone other than `user` performed the action — e.g. an admin acting on this account from the admin panel. Null for every self-service event, where the actor and the subject are already the same person captured in `user`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
