# Generated by Django 5.2.16 on 2026-09-26 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_initial_portal_link_sent_at'),
        ('core', '0004_auditlog_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('user', 'audit_log')},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client Portal Redesign, Phase 5 (the Client Notification Bell). Set instead of `user` for an event that concerns a CLIENT-facing notification (e.g. their invoice was sent, a freelancer replied) rather than a freelancer-facing one. A row has exactly one of user/client set, never both — this table has no concept of one event belonging to both a freelancer and a client at once, and every writer (core.observability.log_event) picks one or the other. A string reference (not a direct import of apps.clients.models.Client) deliberately keeps core/ itself free of any import from an app — the same "core is app-agnostic" discipline core/events.py already documents for itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('client', 'audit_log'), ('user', 'audit_log')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['client', 'created_at'], name='audit_log_client__e2fff3_idx'),
        ),
    ]
