# Generated by Django 5.2.16 on 2026-08-08 18:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_template', models.CharField(choices=[('professional', 'Professional'), ('minimal', 'Minimal'), ('modern', 'Modern')], help_text='Which of the 3 built templates this started from, even for custom designs.', max_length=20)),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('custom', 'Custom'), ('ai_seeded', 'AI-seeded')], default='builtin', max_length=20)),
                ('color_variant', models.CharField(blank=True, help_text='Curated palette key — builtin path only.', max_length=50)),
                ('design_data', models.JSONField(blank=True, default=dict, help_text='Element positions/styles/data-bindings — the single structure feeding editor preview, the portal page, and WeasyPrint rendering.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_designs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('bad_debt', 'Bad Debt')], default='draft', max_length=20)),
                ('sent_via_platform', models.BooleanField(default=False, help_text='Set only by the real /send/ action (not the manual mark-sent flip). Gates reminders only.')),
                ('view_token', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_address', models.TextField(blank=True)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate_to_usd_at_issue', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Cloudinary URL of the frozen, rendered PDF. Populated once by the real /send/ action (or the manual mark-sent flip); never re-rendered afterward even if design is later edited.')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_count', models.SmallIntegerField(default=0)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Percentage per month charged after the due date.', max_digits=5)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval_days', models.PositiveIntegerField(blank=True, choices=[(7, 'Weekly'), (14, 'Bi-weekly'), (30, 'Monthly'), (60, 'Every 2 months'), (90, 'Quarterly'), (365, 'Annually')], null=True)),
                ('recurring_auto_send', models.BooleanField(default=False)),
                ('recurring_paused', models.BooleanField(default=False)),
                ('next_recurring_date', models.DateField(blank=True, null=True)),
                ('escalation_required', models.BooleanField(default=False, help_text='Set after the final reminder is sent — prompts freelancer action.')),
                ('escalation_dismissed', models.BooleanField(default=False, help_text='Set when the freelancer dismisses the escalation prompt without acting.')),
                ('is_one_time_client', models.BooleanField(default=False, help_text='If True, the client is not saved to the address book when this invoice is finalised or sent.')),
                ('pre_payment_status', models.CharField(blank=True, default='', help_text='Status before the first partial payment was recorded; restored exactly when all payments are removed (undo).', max_length=20)),
                ('client_acknowledged', models.BooleanField(default=False)),
                ('client_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Null means a one-time client (see is_one_time_client).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.client')),
                ('exchange_rate_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='payments.exchangeratesnapshot')),
                ('parent_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, help_text="Which saved visual design rendered this invoice's PDF.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicedesign')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sort_order', models.SmallIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePartialPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rate_to_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Value of 1 unit of `currency` in USD, captured at record time.', max_digits=10, null=True)),
                ('source', models.CharField(choices=[('payoneer', 'Payoneer'), ('wise', 'Wise'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('payment_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_partial_payments',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name, e.g. "Web Dev Project".', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('include_client', models.BooleanField(default=False)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('payment_terms', models.PositiveIntegerField(default=30, help_text='Default days until due date.')),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='If True, new invoices start from this preset.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_presets', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_presets',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePresetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('sort_order', models.SmallIntegerField(default=1)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoicepreset')),
            ],
            options={
                'db_table': 'invoice_preset_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_number', models.SmallIntegerField()),
                ('template_used', models.CharField(choices=[('reminder_1', 'Polite (Day 3)'), ('reminder_2', 'Firm (Day 7)'), ('reminder_3', 'Formal (Day 14)'), ('reminder_4', 'Final (Day 30)')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=True)),
                ('days_overdue_at_send', models.SmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_reminders',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceViewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('email_pixel', 'Email pixel'), ('link_click', 'Link click'), ('whatsapp', 'WhatsApp'), ('platform_view', 'Platform view page')], default='link_click', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_view_events',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_source', models.CharField(choices=[('payoneer', 'Payoneer'), ('wise', 'Wise'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='other', max_length=20)),
                ('payment_date', models.DateField()),
                ('client_note', models.TextField(blank=True, help_text='Message from the client about the payment.')),
                ('status', models.CharField(choices=[('pending', 'Pending freelancer review'), ('confirmed', 'Confirmed — payment recorded'), ('rejected', 'Rejected — payment not found')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='invoices.invoice')),
            ],
            options={
                'db_table': 'payment_claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('portal', 'Portal'), ('email_reply', 'Email Reply'), ('app', 'App')], default='app', max_length=20)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, help_text="Only populated for source='email_reply'.")),
                ('attachment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_freelancer_at', models.DateTimeField(blank=True, null=True)),
                ('read_by_client_at', models.DateTimeField(blank=True, null=True)),
                ('author_user', models.ForeignKey(blank=True, help_text="Set when author_type='freelancer'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_comments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='invoice_com_invoice_ea7890_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='invoices_user_id_9940be_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'due_date'], name='invoices_user_id_797f03_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='invoices_status_73cf28_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['next_recurring_date'], name='invoices_next_re_a591be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicereminder',
            unique_together={('invoice', 'reminder_number')},
        ),
    ]
