# Generated by Django 5.2.16 on 2026-08-08 19:02

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=apps.invoices.models._today),
        ),
    ]
