# Generated by Django 5.2.16 on 2026-08-08 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
