# Generated by Django 5.2.16 on 2026-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_refunded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finalised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
