# Generated by Django 5.2.16 on 2026-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_finalised_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reminders_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
