# Generated by Django 5.2.16 on 2026-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_reminders_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_public_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the frozen, rendered PDF. Populated once by _finalise_invoice (the moment an invoice leaves draft — via either the explicit Finalise action or a Mark-as-Sent/real Send called directly on a draft) — never re-rendered afterward even if design is later edited. NOT the real /send/ action (Step 10) — that action was the original design intent here, but the freeze point moved earlier once is_editable was confirmed to already forbid any edit past draft, making a live render on every created-status GET pointless work. See DECISIONS.md.'),
        ),
    ]
