# Generated by Django 5.2.16 on 2026-08-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_pdf_public_id_alter_invoice_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecomment',
            name='unread_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
