# Generated by Django 5.2.16 on 2026-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoicecomment_unread_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='review_note',
            field=models.TextField(blank=True, help_text='Freelancer note on confirm/reject — required on reject (why the claim was not accepted), optional on confirm.'),
        ),
    ]
