# Generated by Django 5.2.16 on 2026-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_paymentclaim_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='formal_notice_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set once a formal notice email is sent. Does not block a deliberate second send — only surfaces that one already went out, same one-shot-timestamp pattern as finalised_at/sent_at.', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_failure_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
