# apps/invoices/migrations/0011_phase0_design_versioning_and_snapshot_foundation.py
# Template Builder 2.0, Phase 0 — purely additive: one nullable JSONField
# on Invoice (unpopulated by any code in this phase) and one new,
# currently-unused standalone table. No existing column, table, or row is
# touched. See LANCERAOS_TEMPLATE_BUILDER_2_PHASE0.md.
# Generated by Django 5.2.16 on 2026-08-22 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_formal_notice_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rendered_design_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceDesignVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('design_data', models.JSONField(help_text='A full, immutable snapshot of InvoiceDesign.design_data at the moment this version was created. Never mutated after creation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='invoices.invoicedesign')),
            ],
            options={
                'db_table': 'invoice_design_versions',
                'ordering': ['design', '-version_number'],
                'indexes': [models.Index(fields=['design', 'version_number'], name='invoice_des_design__a161c4_idx')],
                'unique_together': {('design', 'version_number')},
            },
        ),
    ]
