# apps/invoices/migrations/0013_reversion_drop_design_editor_schema.py
# Full Reversion Plan (back to 3 static templates only), Part 1, step 2 of
# 2. Drops the free-canvas editor's own columns (design_data,
# schema_version lived inside it, source, color_variant) and the
# InvoiceDesignVersion table entirely — InvoiceDesign is reduced to just
# `base_template`, which every real row already held as its own
# independently-tracked column (never derived from design_data at read
# time), verified by 0012 immediately before this runs. Reversible via
# `migrate invoices 0012` (Django replays the removed fields/model back
# in from migration state) — but note that's a SCHEMA-only reversal: the
# actual design_data/color_variant/InvoiceDesignVersion content itself is
# gone for good the moment this runs, recoverable only from the
# pre-reversion backups/ dump, not from `migrate` alone.
# Generated by Django 5.2.16 on 2026-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_verify_design_data_before_reversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedesign',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='invoicedesign',
            name='design_data',
        ),
        migrations.RemoveField(
            model_name='invoicedesign',
            name='source',
        ),
        migrations.AlterField(
            model_name='invoicedesign',
            name='base_template',
            field=models.CharField(choices=[('professional', 'Professional'), ('minimal', 'Minimal'), ('modern', 'Modern')], help_text='Which of the 3 static templates this design renders as.', max_length=20),
        ),
        migrations.DeleteModel(
            name='InvoiceDesignVersion',
        ),
    ]
