# Generated by Django 5.2.16 on 2026-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_remove_invoice_design_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_template',
            field=models.CharField(blank=True, choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple')], help_text="Which of the available templates renders this invoice's PDF.", max_length=20, null=True),
        ),
    ]
