# Generated by Django 5.2.16 on 2026-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_alter_invoice_base_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_template',
            field=models.CharField(blank=True, choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple'), ('free_compact', 'Compact'), ('free_freelancer', 'Freelancer'), ('free_minimal', 'Minimal'), ('free_modern', 'Modern'), ('free_professional', 'Professional'), ('free_business', 'Business')], help_text="Which of the available templates renders this invoice's PDF.", max_length=20, null=True),
        ),
    ]
