# Generated by Django 5.2.16 on 2026-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_invoice_base_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_template',
            field=models.CharField(blank=True, choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple'), ('free_compact', 'Compact'), ('free_freelancer', 'Freelancer'), ('free_minimal', 'Minimal'), ('free_modern', 'Modern'), ('free_professional', 'Professional'), ('free_business', 'Business'), ('pro_executive', 'Executive'), ('pro_studio', 'Studio'), ('pro_signature', 'Signature'), ('pro_editorial', 'Editorial'), ('pro_grid', 'Grid'), ('pro_commerce', 'Commerce'), ('pro_prestige', 'Prestige')], help_text="Which of the available templates renders this invoice's PDF.", max_length=20, null=True),
        ),
    ]
