# Generated by Django 5.2.16 on 2026-08-08 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('rates_to_usd', models.JSONField(help_text='Value of 1 unit of that currency in USD, e.g. {"PKR": 0.0036, "EUR": 1.08, "GBP": 1.27, "USD": 1.0}.')),
                ('source', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_rate_snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
