# Generated by Django 6.0.7 on 2026-07-22 05:01

import apps.users.managers
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('two_fa_code', models.CharField(blank=True, max_length=6)),
                ('two_fa_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_device', models.CharField(blank=True, max_length=300)),
                ('pending_email', models.EmailField(blank=True, max_length=254)),
                ('pending_email_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_history', models.JSONField(blank=True, default=list)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(blank=True, max_length=254)),
                ('step1_token', models.CharField(max_length=128)),
                ('step2_token', models.CharField(blank=True, max_length=128)),
                ('step', models.CharField(choices=[('step1_pending', 'Step 1 — link sent to current email'), ('step1_clicked', 'Step 1 — link clicked, awaiting new email + password'), ('step2_pending', 'Step 2 — activation link sent to new email'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='step1_pending', max_length=20)),
                ('step1_expires_at', models.DateTimeField()),
                ('step2_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_change_requests',
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cnic_encrypted', models.TextField(blank=True)),
                ('cnic_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ntn_encrypted', models.TextField(blank=True)),
                ('ntn_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('pseb_registered', models.BooleanField(default=False)),
                ('pseb_encrypted', models.TextField(blank=True)),
                ('pseb_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('logo_public_id', models.CharField(blank=True, max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('default_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('PKR', 'PKR')], default='USD', max_length=3)),
                ('default_payment_terms', models.PositiveIntegerField(default=30)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('jazzcash_number', models.CharField(blank=True, max_length=20)),
                ('easypaisa_number', models.CharField(blank=True, max_length=20)),
                ('payoneer_email', models.EmailField(blank=True, max_length=254)),
                ('wise_profile_id', models.CharField(blank=True, max_length=100)),
                ('wise_access_token', models.TextField(blank=True)),
                ('wise_refresh_token', models.TextField(blank=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('last_email_changed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_smtp_enabled', models.BooleanField(default=False)),
                ('custom_smtp_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=200)),
                ('custom_smtp_port', models.IntegerField(default=587)),
                ('custom_smtp_username', models.EmailField(blank=True, max_length=254)),
                ('custom_smtp_password', models.TextField(blank=True, help_text='Fernet-encrypted. Never returned in API responses.')),
                ('custom_smtp_use_tls', models.BooleanField(default=True)),
                ('custom_smtp_use_ssl', models.BooleanField(default=False)),
                ('custom_smtp_from_name', models.CharField(blank=True, max_length=200)),
                ('custom_smtp_verified', models.BooleanField(default=False)),
                ('custom_smtp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notif_invoice_events', models.BooleanField(default=True)),
                ('notif_client_messages', models.BooleanField(default=True)),
                ('notif_payments', models.BooleanField(default=True)),
                ('client_onboarding_enabled', models.BooleanField(default=True)),
                ('client_onboarding_message', models.TextField(blank=True, help_text='Custom welcome message for first invoices. Leave blank for the default template.')),
                ('default_send_method', models.CharField(choices=[('email', 'Email only'), ('whatsapp', 'WhatsApp (manual share)'), ('both', 'Email + WhatsApp')], default='email', max_length=10)),
                ('income_type', models.CharField(blank=True, default='it_services', help_text='Primary type of freelance work (for SRO 586 eligibility).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freelancer_profiles',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices',
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20)),
                ('provider_uid', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_social_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified'], name='users_is_emai_476443_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deletion_scheduled_at'], name='users_deletio_591fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', 'step'], name='email_chang_user_id_ec474c_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['step1_token'], name='email_chang_step1_t_ce401d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['step2_token'], name='email_chang_step2_t_e202ff_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'last_used_at'], name='sessions_user_id_8bf6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['refresh_token_hash'], name='sessions_refresh_bbf2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['expires_at'], name='sessions_expires_bbb852_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['token_hash'], name='trusted_dev_token_h_92ee95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersocialaccount',
            unique_together={('provider', 'provider_uid')},
        ),
    ]
