# Generated by Django 5.2.16 on 2026-07-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='income_source',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time freelancer'), ('part_time', 'Part-time, alongside a job'), ('side_income', 'Occasional side income'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='platform_used',
            field=models.CharField(blank=True, choices=[('upwork', 'Upwork'), ('fiverr', 'Fiverr'), ('direct', 'Direct clients'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
