# Generated by Django 5.2.16 on 2026-07-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_freelancerprofile_income_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='custom_name',
            field=models.CharField(blank=True, help_text='User-editable label (e.g. "My MacBook"), shown instead of device_name when set. Set via Settings > Sessions.', max_length=100),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='skip_2fa',
            field=models.BooleanField(default=False, help_text='Whether this device may bypass the 2FA prompt — set only via the explicit "don\'t ask again" checkbox at 2FA-verify time. Distinct from the device simply being recognized: every login creates/matches a TrustedDevice row now, but only this flag grants 2FA-skipping specifically.'),
        ),
    ]
