# Generated by Django 5.2.16 on 2026-07-26 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trusteddevice_custom_name_trusteddevice_skip_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='trusted_device',
            field=models.ForeignKey(blank=True, help_text='The recognized device this session belongs to, when one exists — lets a custom nickname persist across future logins from the same device, rather than needing to be re-set every time a new session is created. Null for sessions created before this link existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='users.trusteddevice'),
        ),
    ]
