# Generated by Django 5.2.16 on 2026-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_terms_accepted_at_user_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False),
        ),
    ]
