# Generated by Django 5.2.16 on 2026-08-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='signature_public_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='signature_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
