# Generated by Django 5.2.16 on 2026-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_freelancerprofile_signature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='formal_notice_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
