# apps/users/migrations/0011_add_invoice_template_preference.py
# Post-Reversion Polish (12 September 2026), Part 2 — replaces the old
# per-user InvoiceDesign row-per-template model with one plain preference
# field. The data step below must run BEFORE apps.invoices' own migration
# that deletes InvoiceDesign (see this migration's `dependencies` — it
# pins against invoices' last migration where InvoiceDesign still has
# real rows, and the invoices-side removal migration in turn depends on
# this one having already run — see that migration's own comment).
# Generated by Django 5.2.16 on 2026-09-12 13:36, data step added by hand.

from django.db import migrations, models


def populate_invoice_template_from_default_design(apps, schema_editor):
    """
    Each user's initial `invoice_template` comes from their current
    `is_default` InvoiceDesign row's `base_template`, if one exists —
    the exact preference `_effective_design`/`invoice_create` already
    read at request time before this migration. A user with no
    InvoiceDesign rows at all (or none marked default) keeps the
    field's own model default, 'professional' — matching this
    integration's very first stated requirement.
    """
    FreelancerProfile = apps.get_model('users', 'FreelancerProfile')
    InvoiceDesign = apps.get_model('invoices', 'InvoiceDesign')

    defaults = InvoiceDesign.objects.filter(is_default=True).select_related('user')
    updated = 0
    for design in defaults:
        FreelancerProfile.objects.filter(user_id=design.user_id).update(invoice_template=design.base_template)
        updated += 1
    print(f'\n[users migration 0011] Set invoice_template from a real default InvoiceDesign for {updated} user(s).')


def noop_reverse(apps, schema_editor):
    # Genuinely irreversible in the data sense (InvoiceDesign rows this
    # read from are gone by the time anyone would reverse this far), but
    # the schema (the field itself) still reverses via the paired
    # RemoveField below — nothing further to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_freelancerprofile_formal_notice_enabled'),
        ('invoices', '0013_reversion_drop_design_editor_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='invoice_template',
            field=models.CharField(choices=[('professional', 'Professional'), ('minimal', 'Minimal'), ('modern', 'Modern')], default='professional', help_text='Which of the 3 static invoice templates a new invoice uses by default.', max_length=20),
        ),
        migrations.RunPython(populate_invoice_template_from_default_design, noop_reverse),
    ]
