# Generated by Django 5.2.16 on 2026-09-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_invoice_template_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='show_lanceraos_branding',
            field=models.BooleanField(default=True),
        ),
    ]
