# Generated by Django 5.2.16 on 2026-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_freelancerprofile_show_lanceraos_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='invoice_template',
            field=models.CharField(choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple')], default='professional', help_text='Which of the available invoice templates a new invoice uses by default.', max_length=20),
        ),
    ]
