# Generated by Django 5.2.16 on 2026-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_freelancerprofile_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='invoice_template',
            field=models.CharField(choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple'), ('free_compact', 'Compact'), ('free_freelancer', 'Freelancer'), ('free_minimal', 'Minimal'), ('free_modern', 'Modern'), ('free_professional', 'Professional'), ('free_business', 'Business')], default='professional', help_text='Which of the available invoice templates a new invoice uses by default.', max_length=20),
        ),
    ]
