# Generated by Django 5.2.16 on 2026-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_freelancerprofile_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='invoice_template',
            field=models.CharField(choices=[('professional', 'Ledger'), ('minimal', 'Minimal'), ('modern', 'Nova'), ('free_essential', 'Essential'), ('free_clean', 'Clean'), ('free_classic', 'Classic'), ('free_simple', 'Simple'), ('free_compact', 'Compact'), ('free_freelancer', 'Freelancer'), ('free_minimal', 'Minimal'), ('free_modern', 'Modern'), ('free_professional', 'Professional'), ('free_business', 'Business'), ('pro_executive', 'Executive'), ('pro_studio', 'Studio'), ('pro_signature', 'Signature'), ('pro_editorial', 'Editorial'), ('pro_grid', 'Grid'), ('pro_commerce', 'Commerce'), ('pro_prestige', 'Prestige')], default='professional', help_text='Which of the available invoice templates a new invoice uses by default.', max_length=20),
        ),
    ]
