// frontend/scripts/js/dump_blank_design_elements.mjs
//
// PART 3, item 1 — the reverse-direction sibling of scripts/py/dump_fixtures.py
// (that script generates JS test fixtures FROM the real Python
// BUILTIN_DESIGNS; this one generates a real Python-consumed JSON fixture
// FROM the frontend's own real default template, design-editor-v2's
// `initialTemplateState` — the collision-verified, "every catalog element
// present, user removes what they don't want" starting point this editor
// was originally built around).
//
// WHY this exists: apps/invoices/design_templates.py's `get_blank_design_data`
// used to hand-author its own, separate, much sparser "blank" layout
// (just the two structurally mandatory anchors — the line-items table and
// a totals block). That is a second, independently-typed approximation of
// "blank" living a second time in Python, with no mechanical link to the
// frontend's own real default — exactly the kind of duplicated-data drift
// risk this codebase has already been bitten by once (design_seeds.py vs
// design_templates.py, the legacy-vs-production schema split). Rather than
// hand-authoring an equivalent rich layout a second time in Python, this
// script runs the ACTUAL frontend adapter (`templateToDesignData`) against
// the ACTUAL frontend default template and dumps its real output — so the
// backend's "blank" starting content can never independently drift from
// whatever the editor's own real default currently is.
//
// This is a real, structural bundling problem, not a plain Node import:
// initialState.js/elementCatalog.js/designDataAdapter.js all use Vite's
// extensionless-import convention (`from './elementCatalog'`), which plain
// Node ESM resolution rejects outright (ERR_MODULE_NOT_FOUND, confirmed
// directly) — so this script bundles the real source files with esbuild
// (already a transitive dependency of vite, no new package added) before
// evaluating them, rather than hand-copying their logic.
//
// Run from anywhere (uses import.meta.url to locate paths); writes into
// apps/invoices/data/blank_design_rich_elements.json — checked in,
// regenerated by RE-RUNNING THIS SCRIPT whenever initialState.js/
// elementCatalog.js/designDataAdapter.js's own default layout changes, never
// hand-edited (its own header field records the exact command that
// produced it, matching dump_fixtures.py's own convention, so a
// stale-looking diff is immediately traceable rather than silently trusted).
//
// Deliberately dumps ONLY `header.elements`/`flow.elements` — never `page`.
// The frontend's own default template's `page` is a generic, zero-margin
// 210x297 canvas with no notion of a real base_template's actual margins/
// sidebar; `get_blank_design_data` supplies the real page geometry itself,
// per base_template, exactly as it already did before this change (see
// that function's own docstring) — only the CONTENT is sourced from here.
import * as esbuild from 'esbuild';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');
const ENTRY_SOURCE = `
import { initialTemplateState } from '${path.resolve(HERE, '../../src/pages/design-editor-v2/data/initialState.js')}';
import { templateToDesignData } from '${path.resolve(HERE, '../../src/pages/design-editor-v2/adapter/designDataAdapter.js')}';
globalThis.__DUMP_RESULT__ = templateToDesignData(initialTemplateState);
`;

const OUT_PATH = path.join(REPO_ROOT, 'apps', 'invoices', 'data', 'blank_design_rich_elements.json');

async function main() {
  const bundled = await esbuild.build({
    stdin: { contents: ENTRY_SOURCE, resolveDir: HERE, loader: 'js' },
    bundle: true,
    platform: 'node',
    format: 'esm',
    write: false,
  });
  const code = bundled.outputFiles[0].text;
  const tmpModulePath = path.join(HERE, `.dump_blank_design_elements.bundle.${Date.now()}.mjs`);
  writeFileSync(tmpModulePath, code);
  try {
    await import(`file://${tmpModulePath}`);
  } finally {
    // Best-effort cleanup — leaving a stray bundle behind on failure isn't
    // worth complicating this script's own error handling for.
    try {
      const { unlinkSync } = await import('node:fs');
      unlinkSync(tmpModulePath);
    } catch {
      // ignore
    }
  }

  const { designData, warnings } = globalThis.__DUMP_RESULT__;
  if (warnings.length) {
    console.warn('templateToDesignData warnings (non-fatal, review before committing):');
    for (const w of warnings) console.warn(`  - ${w}`);
  }

  const output = {
    _generated_by: 'node frontend/scripts/js/dump_blank_design_elements.mjs',
    _source: 'frontend/src/pages/design-editor-v2/data/initialState.js (initialTemplateState), '
      + 'converted via frontend/src/pages/design-editor-v2/adapter/designDataAdapter.js (templateToDesignData)',
    _do_not_hand_edit: true,
    header: designData.header,
    flow: designData.flow,
  };

  mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, JSON.stringify(output, null, 2) + '\n');
  console.log(`wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
