# Generated by Django 5.2.16 on 2026-08-08 16:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #3B82F6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_tags',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_payment_terms', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Archive flag — False means archived, not deleted.')),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('flag_type', models.CharField(blank=True, choices=[('payment_risk', 'Payment Risk'), ('communication', 'Communication Issue'), ('other', 'Other')], max_length=30)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('auto_flagged', models.BooleanField(default=False)),
                ('portal_token', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='clients', to='clients.clienttag')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_client_notes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='clients.client')),
            ],
            options={
                'db_table': 'client_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'created_at'], name='client_note_client__80ca07_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'is_active'], name='clients_user_id_ec8f92_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'email'], name='clients_user_id_2fd703_idx'),
        ),
    ]
