# Generated by Django 5.2.16 on 2026-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientportalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='initial_portal_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
