# Generated by Django 5.2.16 on 2026-07-31 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_sessions',
                'indexes': [models.Index(fields=['user', 'last_used_at'], name='admin_sessi_user_id_704f71_idx'), models.Index(fields=['refresh_token_hash'], name='admin_sessi_refresh_729830_idx'), models.Index(fields=['expires_at'], name='admin_sessi_expires_3c8288_idx')],
            },
        ),
    ]
